### PR TITLE
#33 add latest c5 release

### PR DESCRIPTION
**Pull request by 1stthomas**

### CODE REVIEW

**Comment by 1stthomas** [comment]
`Invalid starting point: elemental_blank` I don't see the problem..

**Comment by mlocati** [comment]
> `Invalid starting point: elemental_blank` on the "Checking required preconditions" task.
> I don't see the problem..

Since https://github.com/concretecms/concretecms/pull/11149, the `elemental_blank` starting point has been removed.

For versions greater than 9.1.3 we can to use `atomik_blank` instead.

**Comment by 1stthomas** [comment]
@mlocati thank you!

**Comment by mlocati** [comment]
@1stthomas This pull request (#34) had an error that I fixed with #35.

It's not your fault: the problem is that maintaining this list of tags is a nightmare.

So, [I rewrote](https://github.com/concrete5-community/docker5/pull/36) the way we define the list of versions: we now have to simply update the [`data/versions.json`](https://github.com/concrete5-community/docker5/blob/main/data/versions.json) file.

Furthermore, I'm working on a GitHub Action that automatically checks for new ConcreteCMS versions, and creates a pull requests if needed.

**Pull request merged**
